FROM registry.lazycat.cloud/lzc/lzcapp:3.20.3

RUN apk add --no-cache go
WORKDIR /app
COPY main /app/app
COPY run.sh /app/run.sh
COPY frp /app/frp
RUN chmod +x /app/run.sh /app/app
COPY web /app/web

EXPOSE 3000
CMD ["sh", "-lc", "trap : TERM INT; sleep infinity & wait"]
