package: cloud.lazycat.app.lzc-frpc # app的唯一标识符
version: 0.0.1 # app的版本
name: FRPC 面板 # app名称
description: # app描述
author: KevinZonda
license: https://choosealicense.com/licenses/mit/
homepage: # 出现bug时候提交反馈的地方
